{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "tendermint_consensus_num_txs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voting Round",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "tendermint_consensus_rounds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "tendermint_mempool_size", "legendFormat": "__auto" }
   ]
  }
 ]
}