---
# tasks file for role-prometheus
- name: Create prometheus yaml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ ansible_env.HOME }}/prometheus.yml"
- name: Run prometheus
  ansible.builtin.command: docker run \
    -d \
    -p 9090:9090 \
    -v {{ ansible_env.HOME }}/prometheus.yml:/etc/prometheus/prometheus.yml \
    prom/prometheus:v{{ prometheus_version }}
  become: yes
